### ISSUE TITLE
Order in 'Select version'

### ISSUE THREAD

**Issue by taroth21** [SUSEdoc/documentation.suse.com-issues#1] opened 2019-09-18 12:00 UTC
'Select version' shows the oldest product versions first, we should consider if using the revert order would not make more sense: from most recent to older versions.

**Comment by fsundermeyer** [comment] 2019-09-20 14:39
Duplicate of https://github.com/openSUSE/docserv/issues/227

**Closed by fsundermeyer** 2019-09-20 14:39 UTC
Labels: duplicate
