### ISSUE TITLE
Categorize the "additional documents" at the bottom of the product doc page 

### ISSUE THREAD

**Issue by chabowski** [SUSEdoc/documentation.suse.com-issues#4] opened 2019-09-18 17:46 UTC
At the bottom of the product pages there are several documents such as e.g. Release Notes and Best Practices. Can we categorize that? It looks quite unclear currently.

I think Release notes are so important that they deserve their own category.

And the other docs could be listed under a category "Additional Documents" or, if there are many best practices, a category "Best Practices".

**Comment by fsundermeyer** [comment] 2019-09-20 14:42
Duplicate of https://github.com/openSUSE/docserv/issues/231

**Closed by fsundermeyer** 2019-09-20 14:42 UTC
Labels: duplicate
